name: label_it
on: 
  pull_request:
    branches:
      - master 

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GT }}"
        configuration-path: .github/label_it_all.yml  //change it before commit
