name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.0
        with:
          repo-token: "${{ secrets.GT }}"
          configuration-path: .github/label_it_all.yml.yml
          enable-versioned-regex: 0
